name: watersheds
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - gdal
  - geopandas
  - matplotlib
  - numpy
  - pandas
  - rasterio
  - richdem
  - scikit-learn
  - scipy
  - jupyterlab
  - rasterstats